name: eventy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # State management.
  flutter_bloc: ^9.1.0
  # for dependency injection
  get_it: ^8.0.3
  # --Networking--
  # -A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.7.0
  # -A dio client generator.
  pretty_dio_logger: ^1.4.0
  # -Discovering the state of the network.
  connectivity_plus: ^6.1.2
  # --Localization--
  intl: ^0.19.0
  # Customize Flutter's default white native splash screen
  flutter_native_splash: ^2.4.4
  # Cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.4.1
  # For custom icons
  iconsax: ^0.0.8
  # Render After Effects animations natively on Flutter.
  lottie: ^3.3.1
  # A carousel slider widget, support infinite scroll and custom child widget.
  smooth_page_indicator: ^1.2.0+3
  # Selecting images from the Android and iOS image library
  #
  dartz: ^0.10.1
  provider: ^6.1.4
  flutter_gemini: ^3.0.0
  dash_chat_2: ^0.0.21
  flutter_svg: ^2.0.17
  # Highly customizable, feature-packed calendar widget for Flutter.
  table_calendar: ^3.1.3
  flutter_map: ^8.0.0
  location: ^8.0.0
  latlong2: ^0.9.1
  shared_preferences: ^2.5.2
  equatable: ^2.0.7
  logger: ^2.5.0
  pinput: ^5.0.1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  webview_flutter: ^4.10.0
  animations: ^2.0.11
  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.1.2
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/user/
    - assets/images/animations/
    - assets/images/
    - assets/images/auth/
    - assets/icons/chat-bot/
    - assets/images/events/
    - assets/logos/eventy/
    - assets/images/default/
    - assets/images/onboarding/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic